# УКАЗЫВАЕМ СВОЙ ИНТЕРФЕЙС!
ISP_INTERFACE="eth2.4"

#-debug=@/opt/var/log/nfqws2.log
NFQWS_BASE_ARGS="--lua-init=@/opt/etc/nfqws2/lua/zapret-lib.lua
                  --lua-init=@/opt/etc/nfqws2/lua/zapret-antidpi.lua
                  --blob=quic_initial:@/opt/etc/nfqws2/blobs/quic_initial.bin
                  --blob=tls_google:@/opt/etc/nfqws2/blobs/tls_clienthello_www_google_com.bin
                  --blob=stun:@/opt/etc/nfqws2/blobs/stun.bin
                  --blob=blob_zero:0x00000000"

# Сбрасываем стандартные переменные, чтобы не мешали CUSTOM_ARGS
NFQWS_ARGS=""
NFQWS_ARGS_QUIC=""
NFQWS_ARGS_UDP=""
NFQWS_EXTRA_ARGS=""
                 
NFQWS_ARGS_CUSTOM="
--filter-udp=443 
--filter-l7=quic 
--payload=quic_initial 
--lua-desync=fake:blob=quic_initial:repeats=11
--new

--filter-udp=590-600,1400,3478-3481,5349,19294-19344,50000-65535 
--filter-l7=wireguard,stun,discord,mtproto 
--out-range=-n2 
--payload=wireguard_initiation,wireguard_response,wireguard_cookie,stun,discord_ip_discovery,mtproto_initial 
--lua-desync=fake:blob=blob_zero:repeats=11 
--new

--filter-tcp=2053,2083,2087,2096,5222,8443 
--hostlist-domains=discord.media 
--payload=tls_client_hello 
--lua-desync=hostfakesplit:host=www.google.com:repeats=4:tcp_ts:ip_ttl=2 
--new

--filter-tcp=80 
--filter-l7=http 
--hostlist-exclude=/opt/etc/nfqws2/lists/exclude.list
--payload=http_req
--lua-desync=fakeddisorder:pos=host:seqovl=1:repeats=2 
--new

--filter-tcp=443
--filter-l7=tls
--hostlist-exclude=/opt/etc/nfqws2/lists/exclude.list
--payload=tls_client_hello
--lua-desync=multisplit:pos=1,midsld,sniext+1:seqovl=100:seqovl_pattern=stun:repeats=2-4:badsum:badseq:md5sig
--lua-desync=fake:blob=tls_google:tls_mod=rnd,dupsid,sni=www.google.com:tcp_ts=-1500:badsum:badseq:md5sig:tcp_md5:repeats=5
--lua-desync=hostfakesplit:host=www.google.com:midhost=midsld-2:repeats=4:ip_ttl=2

"

# 5222 - TCP порт telegram, иногда используется вместо 443
# 2053,2083,2087,2096,8443 - Discord
TCP_PORTS=80,443,2053,2083,2087,2096,5222,8443
# 443 (UDP) - YouTube (QUIC), а также маскирующиеся прокси Telegram и Discord
# 590-600 - Telegram звонки исходящие
# 1400 - Telegram STUN звоннки исходящие
# 3478-3481, 5349 - STUN/TURN звонки Discord и мб где-то еще
# 19294-19344 - Discord Voice (основной рабочий диапазон для голоса и стримов "Go Live")
# 50000-65535 - Игровой диапазон (Dota 2, CS2, Valorant и др., а также резервные порты Discord)
UDP_PORTS=443,590:600,1400,3478:3481,5349,19294:19344,49152:65535
#--------------------------------------------------------------------------------------------OPTION-------------------------------------------------------------

NFQWS_ARGS_IPSET="--ipset=/opt/etc/nfqws2/lists/ipset.list --ipset-exclude=/opt/etc/nfqws2/lists/ipset_exclude.list"

# 7. ОБЩИЕ НАСТРОЙКИ (без изменений)
IPV6_ENABLED=0
POLICY_NAME="nfqws"
LOG_LEVEL=0
LOG_DEBUG_PATH="@/opt/var/log/nfqws2-debug.log"
NFQUEUE_NUM=300
USER=nobody
CONFIG_VERSION=3
# Режим работы политики доступа
# 0 - обрабатывается трафик только для устройств в политике
# 1 - обрабатывается трафик для всех устройств, кроме добавленных в политику
POLICY_EXCLUDE=1
